version: '3.8'

services:
  # PostGIS Database for storing AOI geometries and results
  db:
    image: postgis/postgis:15-3.3
    container_name: kelpie-db
    environment:
      POSTGRES_DB: kelpie_carbon
      POSTGRES_USER: kelpie
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kelpie -d kelpie_carbon"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kelpie-api
    environment:
      - DATABASE_URL=postgresql://kelpie:${POSTGRES_PASSWORD:-secure_password_change_me}@db:5432/kelpie_carbon
      - MODEL_PATH=/app/models/biomass_rf.pkl
    volumes:
      - ./models:/app/models:ro
      - ./dashboard/dist:/app/dashboard/dist:ro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: kelpie-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgis_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: kelpie-network 