[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p dashboard/dist"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT" 