services:
  - type: web
    name: kelpie-carbon-api
    env: python
    buildCommand: pip install -r requirements.txt && cd dashboard && npm install && npm run build
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: "10000"

  - type: static
    name: kelpie-carbon-dashboard
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: ./dashboard/dist
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 