services:
  - type: web
    name: kelpie-carbon-api
    env: python
    buildCommand: pip install -r requirements.txt && cd dashboard && npm install && npm run build && cd ..
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: "10000" 